# Generated by Django 4.2.15 on 2024-08-22 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=24)),
                ('account_type', models.CharField(choices=[(1, 'DEBIT'), (2, 'CRADIT')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=-500, max_digits=10)),
                ('limit', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=-500, max_digits=10), max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[(1, 'EXPENSE'), (2, 'INCOME')], max_length=15)),
                ('transaction_ammount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('transfer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='bank_transaction.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=40, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_purpose', to='bank_transaction.transaction')),
            ],
        ),
    ]
